Repository wecode-bootcamp-korea/32-2nd-WeEats-frontend, pull requests merged in 2022-05, with the labels that each got.

#1 [32기 최규성] Footer 레이아웃
  src/components/Footer/Footer.js
  src/components/Footer/Footer.style.js
Labels: Status: Accepted

#2 [32기 최규성] Nav 레이아웃 로그인 기능 구현
  .gitignore
  package-lock.json
  public/images/.md
  public/images/common/kakao_login.png
  public/images/common/loginBanner.png
  public/images/common/weEatsLogo.png
  public/index.html
  src/Router.js
  src/asset/images/.md
  src/auth.js
  src/components/Hooks/useLockBodyScroll.js
  src/components/LoginModal/LoginModal.js
  src/components/LoginModal/LoginModal.style.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.style.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/OAuth/OAuth.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청

#6 [32기 최규성] 카카오 지도 api 구현 및 공공데이터 활용
  .env
  package-lock.json
  package.json
  public/index.html
  src/components/KaKaoMap/KaKaoMap.js
Labels: Status: 리뷰 요청

#5 [32기 안훈기] 식당 리스트 구현
  package-lock.json
  package.json
  public/data/List/ListData.json
  public/images/Main/chinese.png
  public/images/Main/dessert.png
  public/images/Main/japanese.png
  public/images/Main/korean.png
  public/images/Main/vietnamese.png
  public/images/Main/western.png
  src/Router.js
  src/pages/List/CategoryList.js
  src/pages/List/List.js
  src/pages/List/MainList/MainList.js
  src/pages/List/MainList/Restaurant.js
  src/pages/List/Pick/BestRestaurant.js
  src/pages/List/Pick/Pick.js
  src/pages/List/SideCategory.js
Labels: Status: 리뷰 요청

#4 [32기 이지수]Modify : 리뷰 반영 및 수정 , style 폴더로 styled-components 분리
  package-lock.json
  package.json
  public/data/Mock.json
  public/data/ReservationMock.json
  public/data/checkTime.json
  public/index.html
  src/Router.js
  src/components/Footer/Footer.style.js
  src/components/Nav/Nav.style.js
  src/pages/NotFound.js
  src/pages/OAuth/OAuth.js
  src/pages/Reservations/Button.js
  src/pages/Reservations/Maps.js
  src/pages/Reservations/ReservationCalendar.js
  src/pages/Reservations/ReservationForm.js
  src/pages/Reservations/Reservations.js
  src/pages/Reservations/StoreInfo.js
  src/pages/Reservations/Toggle.js
  src/pages/Reservations/styles/ReservationCalendar.styled.js
  src/pages/Reservations/styles/ReservationForm.styled.js
  src/pages/Reservations/styles/Reservations.styled.js
  src/pages/Reservations/styles/StoreInfo.styled.js
  src/pages/Reservations/styles/Toggle.styled.js
  src/styles/GlobalStyles.js
Labels: Status: Conflict 해결 요청

#7 [32기이지수] Add:컴포넌트추가, 파일분리
  public/data/Mock.json
  public/data/userData.json
  public/images/KERO.jpg
  src/Router.js
  src/components/Hooks/useFetchUser.js
  src/components/Nav/Nav.js
  src/pages/MyPage/GoList.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/ReservationInfo.js
  src/pages/MyPage/ReservationInfoList.js
  src/pages/MyPage/ReservationInfoWapper.js
  src/pages/MyPage/UserInfo.js
  src/pages/MyPage/styles/GoList.styled.js
  src/pages/MyPage/styles/MyPage.styled.js
  src/pages/MyPage/styles/ReservationInfo.styled.js
  src/pages/MyPage/styles/ReservationInfoWapper.style.js
  src/pages/MyPage/styles/UserInfo.styled.js
  src/pages/Reservations/Maps.js
  src/pages/Reservations/ReservationForm.js
  src/pages/Reservations/Reservations.js
  src/pages/Reservations/StoreInfo.js
  src/pages/Reservations/Toggle.js
  src/pages/Reservations/styles/ReservationForm.styled.js
  src/pages/Reservations/styles/Toggle.styled.js
Labels: Status: 리뷰 요청
